#!/usr/bin/env bash
# Bash script that installs nginx on a server

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 Moved Permanently;}' /etc/nginx/sites-available/default
service nginx start
