#!/usr/bin/env bash
# This script setup and configure a web server

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 "Moved Permanently";}' /etc/nginx/sites-available/default
sed -i '/^}$/i \ \n\tlocation @404 {return 404 "Ceci n'\''est pas une page\\n";}' /etc/nginx/sites-available/default
sed -i 's/=404/@404/g' /etc/nginx/sites-available/default
sed -i "0,/location \/ {/s/location \/ {/&\n\t\tadd_header X-Served-By '$HOSTNAME';/" /etc/nginx/sites-available/default
service nginx start
